language: node_js
node_js:
- stable
before_script:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
- export PATH="$HOME/.yarn/bin:$PATH"
- yarn install
script:
- yarn lint
- yarn test